[2021-05-03 20:26:19,154: INFO/MainProcess] Connected to redis://localhost:6379//
[2021-05-03 20:26:19,163: INFO/MainProcess] mingle: searching for neighbors
[2021-05-03 20:26:20,180: INFO/MainProcess] mingle: all alone
[2021-05-03 20:26:20,203: WARNING/MainProcess] /home/lilbiji/.local/lib/python3.8/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2021-05-03 20:26:20,203: INFO/MainProcess] celery@kali ready.
[2021-05-03 20:48:15,515: ERROR/MainProcess] Received unregistered task of type 'print_msg_main'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[["Hello"], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (84b)
Traceback (most recent call last):
  File "/home/lilbiji/.local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 555, in on_task_received
    strategy = strategies[type_]
KeyError: 'print_msg_main'
[2021-05-03 20:48:25,450: ERROR/MainProcess] Received unregistered task of type 'print_msg_main'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[["Hello"], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (84b)
Traceback (most recent call last):
  File "/home/lilbiji/.local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 555, in on_task_received
    strategy = strategies[type_]
KeyError: 'print_msg_main'
[2021-05-03 20:48:25,618: ERROR/MainProcess] Received unregistered task of type 'print_time'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/home/lilbiji/.local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 555, in on_task_received
    strategy = strategies[type_]
KeyError: 'print_time'
[2021-05-03 20:48:35,443: ERROR/MainProcess] Received unregistered task of type 'print_msg_main'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[["Hello"], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (84b)
Traceback (most recent call last):
  File "/home/lilbiji/.local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 555, in on_task_received
    strategy = strategies[type_]
KeyError: 'print_msg_main'
[2021-05-03 20:48:45,450: ERROR/MainProcess] Received unregistered task of type 'print_msg_main'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[["Hello"], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (84b)
Traceback (most recent call last):
  File "/home/lilbiji/.local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 555, in on_task_received
    strategy = strategies[type_]
KeyError: 'print_msg_main'
[2021-05-03 20:48:45,618: ERROR/MainProcess] Received unregistered task of type 'get_calculation'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[10, 20], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (83b)
Traceback (most recent call last):
  File "/home/lilbiji/.local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 555, in on_task_received
    strategy = strategies[type_]
KeyError: 'get_calculation'
[2021-05-03 20:48:45,625: ERROR/MainProcess] Received unregistered task of type 'print_time'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)
Traceback (most recent call last):
  File "/home/lilbiji/.local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 555, in on_task_received
    strategy = strategies[type_]
KeyError: 'print_time'
[2021-05-03 20:48:48,835: INFO/MainProcess] Connected to redis://localhost:6379//
[2021-05-03 20:48:48,844: INFO/MainProcess] mingle: searching for neighbors
[2021-05-03 20:48:49,861: INFO/MainProcess] mingle: all alone
[2021-05-03 20:48:49,887: WARNING/MainProcess] /home/lilbiji/.local/lib/python3.8/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2021-05-03 20:48:49,887: INFO/MainProcess] celery@kali ready.
[2021-05-03 20:48:55,450: ERROR/MainProcess] Received unregistered task of type 'print_msg_main'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[["Hello"], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (84b)
Traceback (most recent call last):
  File "/home/lilbiji/.local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 555, in on_task_received
    strategy = strategies[type_]
KeyError: 'print_msg_main'
[2021-05-03 20:49:05,451: ERROR/MainProcess] Received unregistered task of type 'print_msg_main'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[["Hello"], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (84b)
Traceback (most recent call last):
  File "/home/lilbiji/.local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 555, in on_task_received
    strategy = strategies[type_]
KeyError: 'print_msg_main'
[2021-05-03 20:49:05,681: INFO/MainProcess] Received task: print_time[347bc26d-ee69-4c8e-b3ce-05f3f51e0040]  
[2021-05-03 20:49:05,685: WARNING/ForkPoolWorker-1] Current Time is 20:49:05
[2021-05-03 20:49:05,691: INFO/ForkPoolWorker-1] Task print_time[347bc26d-ee69-4c8e-b3ce-05f3f51e0040] succeeded in 0.0068244120047893375s: None
